webhook: url
port: 8010
enable:
  advancements: false
  balance-api: false
  supporter-bypass: false
  maintenance: false
color:
  system: 65535
  join: 65280
  sami: 15369278
  leave: 16711680
  death: 8388736
  advancement: 65535