name: SamiPlugin
version: ${project.version}
main: com.samifying.plugin.SamiPlugin
api-version: 1.18
description: Handles Discord and balance integration
author: Pequla
load: STARTUP
depend: [ Vault, LuckPerms ]
commands:
  discord:
    description: Admin command
    permission: sami.plugin.discord
  lookup:
    description: Player lookup
    permission: sami.plugin.lookup
  lore:
    description: Change item lore
    permission: sami.plugin.lore
permissions:
  sami.plugin.discord:
    description: Discord command permission
  sami.plugin.lookup:
    description: Lookup command permission
  sami.plugin.lore:
    description: Lore command permission